apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: component-docs
  description: A test document to check git repos caching in backstage
  labels:
    system: public-websites
  annotations:
    backstage.io/techdocs-ref: dir:./
  tags:
    - java
    
spec:
  type: service
  lifecycle: production
  owner: nidhi-sinha
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
